'use client'

/**
 * Biblioteca de ícones padronizada para categorias (Painel Master).
 *
 * O admin digita o nome da categoria e escolhe um "iconzinho" aqui —
 * assim todas as categorias seguem a mesma linguagem visual no portal.
 *
 * ⚠️ Todos os ícones são do lucide-react (já instalado). Para adicionar
 * um novo, importe o ícone e adicione uma entrada na lista com um label
 * em PT-BR (usado na busca do seletor).
 */
import {
  Accessibility,
  Activity,
  AirVent,
  Ambulance,
  Anchor,
  Angry,
  Annoyed,
  Aperture,
  Apple,
  Atom,
  AtSign,
  Award,
  Axe,
  Baby,
  Backpack,
  BadgeCheck,
  Banana,
  Bandage,
  Banknote,
  Bath,
  Battery,
  BatteryCharging,
  Beaker,
  Bean,
  Bed,
  BedDouble,
  Beef,
  Beer,
  BeerOff,
  Bell,
  BellRing,
  Bike,
  Binoculars,
  Bird,
  Bone,
  Book,
  BookHeart,
  Bookmark,
  BookMarked,
  BookOpen,
  BookText,
  Bot,
  Brain,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  CalendarDays,
  CalendarHeart,
  Camera,
  Candy,
  CandyCane,
  Car,
  CarFront,
  Carrot,
  Cat,
  ChartColumn,
  ChartLine,
  ChefHat,
  Church,
  Cigarette,
  Citrus,
  Clapperboard,
  Clock,
  Cloud,
  CloudRain,
  CloudSun,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Construction,
  Contact,
  Cookie,
  CookingPot,
  Cpu,
  CreditCard,
  Croissant,
  Cross,
  Crosshair,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dice5,
  Dices,
  Disc,
  Disc3,
  Dna,
  Dog,
  Donut,
  Drama,
  Drill,
  Droplet,
  Droplets,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  Earth,
  Egg,
  EggFried,
  Eye,
  Fan,
  Feather,
  Film,
  Fingerprint,
  Fish,
  FishSymbol,
  Flag,
  FlagTriangleRight,
  Flame,
  Flashlight,
  FlaskConical,
  Flower,
  Flower2,
  Footprints,
  Frown,
  Fuel,
  Gamepad,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Glasses,
  GlassWater,
  Globe,
  Goal,
  GraduationCap,
  Grape,
  Guitar,
  Ham,
  Hamburger,
  Hammer,
  Hand,
  HandHeart,
  HandHelping,
  HandMetal,
  HardHat,
  Hash,
  Headphones,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  Heater,
  Home,
  Hop,
  Hospital,
  Hourglass,
  IceCream,
  IceCreamBowl,
  Image as ImageIcon,
  Images,
  Infinity as InfinityIcon,
  Joystick,
  Key,
  KeyRound,
  Lamp,
  LampDesk,
  Landmark,
  Languages,
  Laptop,
  Laugh,
  Leaf,
  LeafyGreen,
  Library,
  LifeBuoy,
  Lock,
  Lollipop,
  Luggage,
  Mail,
  Map as MapIcon,
  MapPin,
  Mars,
  Martini,
  Medal,
  Megaphone,
  Meh,
  MessageCircle,
  MessageCircleHeart,
  MessageSquare,
  Mic,
  Mic2,
  Microscope,
  Microwave,
  Milk,
  Monitor,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  Music,
  Music2,
  Music3,
  Music4,
  Newspaper,
  Notebook,
  NotebookPen,
  Nut,
  Orbit,
  Origami,
  Package,
  PackageOpen,
  Paintbrush,
  PaintBucket,
  PaintRoller,
  Palette,
  Panda,
  PartyPopper,
  PawPrint,
  Pen,
  Pencil,
  PencilRuler,
  PenLine,
  PenTool,
  Percent,
  Phone,
  Piano,
  Pickaxe,
  PiggyBank,
  Pill,
  Pipette,
  Pizza,
  Plane,
  PlaneTakeoff,
  Plug,
  Podcast,
  Popcorn,
  Popsicle,
  Presentation,
  Puzzle,
  QrCode,
  Quote,
  Rabbit,
  Radio,
  Rainbow,
  Rat,
  Receipt,
  Recycle,
  Refrigerator,
  Ribbon,
  Rocket,
  Ruler,
  Sailboat,
  Sandwich,
  Satellite,
  ScanLine,
  School,
  Scissors,
  Server,
  Settings,
  Shell,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shrub,
  Smartphone,
  SmilePlus,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  Speech,
  Squirrel,
  Star,
  StarHalf,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Sword,
  Syringe,
  Tablets,
  Tag,
  Tags,
  Target,
  Telescope,
  Tent,
  TentTree,
  Terminal,
  Text,
  Thermometer,
  ThumbsUp,
  Ticket,
  Tickets,
  Timer,
  Tractor,
  TrafficCone,
  Train,
  TrainFront,
  Trash2,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Tv2,
  Type,
  Umbrella,
  University,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Vegan,
  Venus,
  Video,
  Volleyball,
  Volume2,
  Wallet,
  Wand2,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
  Worm,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export type CategoryIconDef = {
  /** slug salvo no banco (Category.icon) */
  name: string
  /** rótulo em PT-BR usado na busca do seletor */
  label: string
  Icon: LucideIcon
}

export const CATEGORY_ICONS: CategoryIconDef[] = [
  { name: 'heart', label: 'amor coração casal', Icon: Heart },
  { name: 'heart-handshake', label: 'amizade gratidão', Icon: HeartHandshake },
  { name: 'coffee', label: 'café caneca morning', Icon: Coffee },
  { name: 'flame', label: 'fogo trendy viral', Icon: Flame },
  { name: 'star', label: 'estrela favorito', Icon: Star },
  { name: 'sparkles', label: 'brilho mágico', Icon: Sparkles },
  { name: 'zap', label: 'energia raio', Icon: Zap },
  { name: 'party-popper', label: 'festa comemoração', Icon: PartyPopper },
  { name: 'cake', label: 'aniversário bolo', Icon: Cake },
  { name: 'gift', label: 'presente brinde', Icon: Gift },
  { name: 'crown', label: 'rei rainha nobre', Icon: Crown },
  { name: 'medal', label: 'medalha premiado', Icon: Medal },
  { name: 'trophy', label: 'troféu campeão', Icon: Trophy },
  { name: 'target', label: 'alvo meta', Icon: Target },
  { name: 'users', label: 'pessoas equipe família', Icon: Users },
  { name: 'baby', label: 'bebê maternidade', Icon: Baby },
  { name: 'graduation-cap', label: 'formatura escola aluno', Icon: GraduationCap },
  { name: 'book-open', label: 'livro leitura estudo', Icon: BookOpen },
  { name: 'pencil', label: 'escola professor', Icon: PenTool },
  { name: 'stethoscope', label: 'médica saúde', Icon: Stethoscope },
  { name: 'syringe', label: 'enfermagem enfermeira vacina', Icon: Syringe },
  { name: 'heart-pulse', label: 'saúde hospital', Icon: HeartPulse },
  { name: 'hard-hat', label: 'engenheiro obra', Icon: HardHat },
  { name: 'wrench', label: 'mecânico ferramenta', Icon: Wrench },
  { name: 'hammer', label: 'marceneiro construção', Icon: Hammer },
  { name: 'paintbrush', label: 'pintor artista', Icon: Paintbrush },
  { name: 'palette', label: 'arte cores criativo', Icon: Palette },
  { name: 'brush', label: 'pincel designer', Icon: Brush },
  { name: 'camera', label: 'fotógrafo foto', Icon: Camera },
  { name: 'music', label: 'música nota', Icon: Music },
  { name: 'guitar', label: 'violão banda', Icon: Guitar },
  { name: 'mic', label: 'cantor karaokê', Icon: Mic },
  { name: 'headphones', label: 'dj som fone', Icon: Headphones },
  { name: 'gamepad2', label: 'games videogame', Icon: Gamepad2 },
  { name: 'laptop', label: 'informática ti', Icon: Laptop },
  { name: 'cpu', label: 'tecnologia', Icon: Cpu },
  { name: 'dumbbell', label: 'academia treino', Icon: Dumbbell },
  { name: 'bike', label: 'bike ciclismo', Icon: Bike },
  { name: 'car', label: 'carro motorista uber', Icon: Car },
  { name: 'truck', label: 'caminhoneiro frete', Icon: Truck },
  { name: 'plane', label: 'avião viagem', Icon: Plane },
  { name: 'anchor', label: 'marinha navio', Icon: Anchor },
  { name: 'rocket', label: 'foguete espaço', Icon: Rocket },
  { name: 'chef-hat', label: 'cozinheiro chef', Icon: ChefHat },
  { name: 'utensils', label: 'restaurante comida', Icon: Utensils },
  { name: 'pizza', label: 'pizza pizzaria', Icon: Pizza },
  { name: 'beer', label: 'cerveja bar chope', Icon: Beer },
  { name: 'wine', label: 'vinho taça', Icon: Wine },
  { name: 'ice-cream', label: 'sorvete', Icon: IceCream },
  { name: 'croissant', label: 'padaria pão', Icon: Croissant },
  { name: 'cookie', label: 'biscoito doce', Icon: Cookie },
  { name: 'popcorn', label: 'pipoca cinema', Icon: Popcorn },
  { name: 'cup-soda', label: 'refrigerante suco', Icon: CupSoda },
  { name: 'egg', label: 'páscoa ovo', Icon: Egg },
  { name: 'paw-print', label: 'pet patinha animal', Icon: PawPrint },
  { name: 'dog', label: 'cachorro dog', Icon: Dog },
  { name: 'cat', label: 'gato miau', Icon: Cat },
  { name: 'bird', label: 'pássaro ave', Icon: Bird },
  { name: 'fish', label: 'peixe pescaria', Icon: Fish },
  { name: 'rabbit', label: 'coelho', Icon: Rabbit },
  { name: 'squirrel', label: 'esquilo', Icon: Squirrel },
  { name: 'turtle', label: 'tartaruga', Icon: Turtle },
  { name: 'bug', label: 'inseto joaninha', Icon: Bug },
  { name: 'flower', label: 'flor primavera', Icon: Flower },
  { name: 'flower-2', label: 'flor delicada madrinha', Icon: Flower2 },
  { name: 'leaf', label: 'folha natureza', Icon: Leaf },
  { name: 'tree-pine', label: 'árvore natal pinheiro', Icon: TreePine },
  { name: 'mountain', label: 'montanha aventura', Icon: Mountain },
  { name: 'sun', label: 'sol verão', Icon: Sun },
  { name: 'moon', label: 'lua noite', Icon: Moon },
  { name: 'rainbow', label: 'arco-íris colorido', Icon: Rainbow },
  { name: 'umbrella', label: 'chuva praia', Icon: Umbrella },
  { name: 'waves', label: 'ondas mar praia', Icon: Waves },
  { name: 'snowflake', label: 'frio inverno natal', Icon: Snowflake },
  { name: 'church', label: 'igreja religião', Icon: Church },
  { name: 'cross', label: 'cruz fé cristã', Icon: Cross },
  { name: 'ghost', label: 'fantasma halloween', Icon: Ghost },
  { name: 'ribbon', label: 'laço outubrosa', Icon: Ribbon },
  { name: 'laugh', label: 'engraçado humor meme', Icon: Laugh },
  { name: 'backpack', label: 'mochila volta às aulas', Icon: Backpack },
  { name: 'shopping-bag', label: 'compras loja', Icon: ShoppingBag },
  { name: 'landmark', label: 'banco financeiro', Icon: Landmark },
  { name: 'wallet', label: 'dinheiro economia', Icon: Wallet },
  { name: 'key-round', label: 'chave senha', Icon: KeyRound },
  { name: 'lock', label: 'cadeado bloqueado', Icon: Lock },
  { name: 'footprints', label: 'pegadas caminhada', Icon: Footprints },
  { name: 'wand', label: 'mágica Harry Potter', Icon: Wand2 },

  /* ---- Biblioteca ampliada ---- */
  { name: 'smile-plus', label: 'emoji feliz', Icon: SmilePlus },
  { name: 'heart-crack', label: 'coração partido saudade', Icon: HeartCrack },
  { name: 'hand-heart', label: 'carinho doação solidariedade', Icon: HandHeart },
  { name: 'thumbs-up', label: 'curtir positivo joinha', Icon: ThumbsUp },
  { name: 'hand-metal', label: 'rock metal', Icon: HandMetal },
  { name: 'hand', label: 'mão oi', Icon: Hand },
  { name: 'hand-helping', label: 'ajuda voluntário', Icon: HandHelping },
  { name: 'user-round', label: 'pessoa perfil', Icon: UserRound },
  { name: 'users-round', label: 'grupo amigos turma', Icon: UsersRound },
  { name: 'accessibility', label: 'acessibilidade inclusão', Icon: Accessibility },
  { name: 'venus', label: 'feminino mulher', Icon: Venus },
  { name: 'mars', label: 'masculino homem', Icon: Mars },
  { name: 'dna', label: 'genética biologia', Icon: Dna },
  { name: 'brain', label: 'mente cérebro psicologia', Icon: Brain },
  { name: 'eye', label: 'olho visão óptica', Icon: Eye },
  { name: 'ear', label: 'ouvido audição', Icon: Ear },
  { name: 'glasses', label: 'óculos nerd', Icon: Glasses },
  { name: 'shirt', label: 'camisa roupa moda', Icon: Shirt },
  { name: 'gem', label: 'joia diamante', Icon: Gem },
  { name: 'diamond', label: 'diamante', Icon: Diamond },
  { name: 'watch', label: 'relógio', Icon: Watch },
  { name: 'scissors', label: 'tesoura cabeleireiro barbeiro', Icon: Scissors },
  { name: 'sparkle', label: 'brilho', Icon: Sparkle },
  { name: 'award', label: 'prêmio certificado', Icon: Award },
  { name: 'badge-check', label: 'verificado aprovado', Icon: BadgeCheck },
  { name: 'shield', label: 'proteção escudo', Icon: Shield },
  { name: 'shield-check', label: 'segurança proteção', Icon: ShieldCheck },
  { name: 'sword', label: 'espada medieval', Icon: Sword },
  { name: 'bone', label: 'osso cachorro', Icon: Bone },
  { name: 'bot', label: 'robô ia', Icon: Bot },
  { name: 'atom', label: 'átomo ciência', Icon: Atom },
  { name: 'flask-conical', label: 'química laboratório', Icon: FlaskConical },
  { name: 'microscope', label: 'microscópio biologia', Icon: Microscope },
  { name: 'pill', label: 'farmácia remédio', Icon: Pill },
  { name: 'tablets', label: 'farmacêutica comprimido', Icon: Tablets },
  { name: 'hospital', label: 'hospital clínica', Icon: Hospital },
  { name: 'ambulance', label: 'ambulância socorro', Icon: Ambulance },
  { name: 'activity', label: 'batimentos fisioterapia', Icon: Activity },
  { name: 'bandage', label: 'curativo', Icon: Bandage },
  { name: 'thermometer', label: 'termômetro febre', Icon: Thermometer },
  { name: 'droplet', label: 'gota água', Icon: Droplet },
  { name: 'droplets', label: 'gotas água', Icon: Droplets },
  { name: 'wind', label: 'vento', Icon: Wind },
  { name: 'cloud', label: 'nuvem', Icon: Cloud },
  { name: 'cloud-rain', label: 'chuva', Icon: CloudRain },
  { name: 'cloud-sun', label: 'dia nublado', Icon: CloudSun },
  { name: 'sunrise', label: 'nascer do sol manhã', Icon: Sunrise },
  { name: 'sunset', label: 'pôr do sol', Icon: Sunset },
  { name: 'moon-star', label: 'lua estrela noite', Icon: MoonStar },
  { name: 'star-half', label: 'meia estrela', Icon: StarHalf },
  { name: 'orbit', label: 'órbita planeta espaço', Icon: Orbit },
  { name: 'telescope', label: 'telescópio astronomia', Icon: Telescope },
  { name: 'globe', label: 'mundo planeta', Icon: Globe },
  { name: 'earth', label: 'terra planeta', Icon: Earth },
  { name: 'map', label: 'mapa', Icon: MapIcon },
  { name: 'map-pin', label: 'local lugar', Icon: MapPin },
  { name: 'compass', label: 'bússola aventura', Icon: Compass },
  { name: 'flag', label: 'bandeira', Icon: Flag },
  { name: 'flag-triangle-right', label: 'bandeira corrida', Icon: FlagTriangleRight },
  { name: 'tent', label: 'camping barraca acampamento', Icon: Tent },
  { name: 'tent-tree', label: 'acampamento natureza', Icon: TentTree },
  { name: 'tree-palm', label: 'coqueiro praia férias', Icon: TreePalm },
  { name: 'tree-deciduous', label: 'árvore', Icon: TreeDeciduous },
  { name: 'trees', label: 'floresta', Icon: Trees },
  { name: 'shrub', label: 'arbusto jardim', Icon: Shrub },
  { name: 'leafy-green', label: 'verde folha', Icon: LeafyGreen },
  { name: 'tractor', label: 'trator agro fazenda', Icon: Tractor },
  { name: 'carrot', label: 'cenoura horta', Icon: Carrot },
  { name: 'apple', label: 'maçã fruta', Icon: Apple },
  { name: 'banana', label: 'banana fruta', Icon: Banana },
  { name: 'grape', label: 'uva', Icon: Grape },
  { name: 'citrus', label: 'limão laranja', Icon: Citrus },
  { name: 'sandwich', label: 'lanche sanduíche', Icon: Sandwich },
  { name: 'soup', label: 'sopa', Icon: Soup },
  { name: 'beef', label: 'carne churrasco', Icon: Beef },
  { name: 'drumstick', label: 'frango coxinha', Icon: Drumstick },
  { name: 'ham', label: 'presunto churrasco', Icon: Ham },
  { name: 'candy', label: 'doce bala', Icon: Candy },
  { name: 'candy-cane', label: 'bengala doce natal', Icon: CandyCane },
  { name: 'lollipop', label: 'pirulito doce', Icon: Lollipop },
  { name: 'donut', label: 'rosquinha donut', Icon: Donut },
  { name: 'cake-slice', label: 'fatia bolo', Icon: CakeSlice },
  { name: 'ice-cream-bowl', label: 'sorvete taça', Icon: IceCreamBowl },
  { name: 'popsicle', label: 'picolé', Icon: Popsicle },
  { name: 'milk', label: 'leite', Icon: Milk },
  { name: 'martini', label: 'drink coquetel', Icon: Martini },
  { name: 'glass-water', label: 'água copo', Icon: GlassWater },
  { name: 'beer-off', label: 'sem álcool', Icon: BeerOff },
  { name: 'utensils-crossed', label: 'talheres restaurante', Icon: UtensilsCrossed },
  { name: 'cooking-pot', label: 'panela cozinha', Icon: CookingPot },
  { name: 'microwave', label: 'micro-ondas', Icon: Microwave },
  { name: 'refrigerator', label: 'geladeira', Icon: Refrigerator },
  { name: 'bed', label: 'cama dormir', Icon: Bed },
  { name: 'bed-double', label: 'cama casal', Icon: BedDouble },
  { name: 'bath', label: 'banho banheira', Icon: Bath },
  { name: 'shower-head', label: 'chuveiro', Icon: ShowerHead },
  { name: 'sofa', label: 'sofá casa', Icon: Sofa },
  { name: 'lamp', label: 'abajur', Icon: Lamp },
  { name: 'lamp-desk', label: 'luminária', Icon: LampDesk },
  { name: 'plug', label: 'tomada elétrica', Icon: Plug },
  { name: 'battery', label: 'bateria', Icon: Battery },
  { name: 'battery-charging', label: 'energia', Icon: BatteryCharging },
  { name: 'wifi', label: 'internet', Icon: Wifi },
  { name: 'mail', label: 'e-mail carta', Icon: Mail },
  { name: 'message-circle', label: 'mensagem conversa', Icon: MessageCircle },
  { name: 'message-square', label: 'mensagem', Icon: MessageSquare },
  { name: 'message-circle-heart', label: 'mensagem amor', Icon: MessageCircleHeart },
  { name: 'phone', label: 'telefone', Icon: Phone },
  { name: 'smartphone', label: 'celular', Icon: Smartphone },
  { name: 'at-sign', label: 'arroba internet', Icon: AtSign },
  { name: 'hash', label: 'hashtag', Icon: Hash },
  { name: 'quote', label: 'frases citação', Icon: Quote },
  { name: 'type', label: 'letras tipografia', Icon: Type },
  { name: 'text', label: 'texto', Icon: Text },
  { name: 'languages', label: 'idiomas inglês', Icon: Languages },
  { name: 'newspaper', label: 'jornal notícias', Icon: Newspaper },
  { name: 'megaphone', label: 'megafone marketing', Icon: Megaphone },
  { name: 'bell', label: 'sino', Icon: Bell },
  { name: 'bell-ring', label: 'sino alerta', Icon: BellRing },
  { name: 'calendar', label: 'calendário', Icon: Calendar },
  { name: 'calendar-heart', label: 'data especial', Icon: CalendarHeart },
  { name: 'calendar-days', label: 'datas', Icon: CalendarDays },
  { name: 'clock', label: 'relógio hora', Icon: Clock },
  { name: 'hourglass', label: 'ampulheta tempo', Icon: Hourglass },
  { name: 'timer', label: 'cronômetro', Icon: Timer },
  { name: 'briefcase', label: 'trabalho maleta executivo', Icon: Briefcase },
  { name: 'briefcase-business', label: 'empresário negócios', Icon: BriefcaseBusiness },
  { name: 'building-2', label: 'prédio empresa', Icon: Building2 },
  { name: 'building', label: 'prédio', Icon: Building },
  { name: 'home', label: 'casa lar', Icon: Home },
  { name: 'school', label: 'escola', Icon: School },
  { name: 'library', label: 'biblioteca', Icon: Library },
  { name: 'university', label: 'faculdade universidade', Icon: University },
  { name: 'store', label: 'loja comércio', Icon: Store },
  { name: 'tag', label: 'etiqueta preço', Icon: Tag },
  { name: 'tags', label: 'etiquetas', Icon: Tags },
  { name: 'percent', label: 'desconto promoção', Icon: Percent },
  { name: 'shopping-cart', label: 'carrinho compras', Icon: ShoppingCart },
  { name: 'shopping-basket', label: 'cesta compras', Icon: ShoppingBasket },
  { name: 'package', label: 'pacote encomenda', Icon: Package },
  { name: 'package-open', label: 'caixa entrega', Icon: PackageOpen },
  { name: 'receipt', label: 'recibo', Icon: Receipt },
  { name: 'coins', label: 'moedas dinheiro', Icon: Coins },
  { name: 'banknote', label: 'nota dinheiro', Icon: Banknote },
  { name: 'credit-card', label: 'cartão', Icon: CreditCard },
  { name: 'piggy-bank', label: 'cofrinho economia', Icon: PiggyBank },
  { name: 'calculator', label: 'calculadora contador', Icon: Calculator },
  { name: 'chart-line', label: 'gráfico crescimento', Icon: ChartLine },
  { name: 'chart-column', label: 'gráfico', Icon: ChartColumn },
  { name: 'trending-up', label: 'crescimento sucesso', Icon: TrendingUp },
  { name: 'pen', label: 'caneta', Icon: Pen },
  { name: 'pen-line', label: 'escrita assinatura', Icon: PenLine },
  { name: 'lapis', label: 'lápis', Icon: Pencil },
  { name: 'pencil-ruler', label: 'projeto arquiteto', Icon: PencilRuler },
  { name: 'ruler', label: 'régua', Icon: Ruler },
  { name: 'notebook', label: 'caderno', Icon: Notebook },
  { name: 'notebook-pen', label: 'anotações', Icon: NotebookPen },
  { name: 'book', label: 'livro', Icon: Book },
  { name: 'book-marked', label: 'livro marcado', Icon: BookMarked },
  { name: 'book-heart', label: 'livro romance', Icon: BookHeart },
  { name: 'book-text', label: 'livro texto', Icon: BookText },
  { name: 'bookmark', label: 'marcador', Icon: Bookmark },
  { name: 'feather', label: 'pena', Icon: Feather },
  { name: 'origami', label: 'origami dobradura', Icon: Origami },
  { name: 'rat', label: 'rato', Icon: Rat },
  { name: 'worm', label: 'minhoca', Icon: Worm },
  { name: 'snail', label: 'caracol', Icon: Snail },
  { name: 'fish-symbol', label: 'peixe', Icon: FishSymbol },
  { name: 'shell', label: 'concha praia', Icon: Shell },
  { name: 'egg-fried', label: 'ovo frito', Icon: EggFried },
  { name: 'panda', label: 'panda', Icon: Panda },
  { name: 'beaker', label: 'béquer', Icon: Beaker },
  { name: 'dices', label: 'dados jogo', Icon: Dices },
  { name: 'dice-5', label: 'dado', Icon: Dice5 },
  { name: 'puzzle', label: 'quebra-cabeça autismo', Icon: Puzzle },
  { name: 'joystick', label: 'joystick', Icon: Joystick },
  { name: 'gamepad', label: 'controle game', Icon: Gamepad },
  { name: 'drama', label: 'teatro máscaras', Icon: Drama },
  { name: 'clapperboard', label: 'cinema filme', Icon: Clapperboard },
  { name: 'film', label: 'filme', Icon: Film },
  { name: 'tv', label: 'televisão', Icon: Tv },
  { name: 'tv-2', label: 'televisão', Icon: Tv2 },
  { name: 'monitor', label: 'computador', Icon: Monitor },
  { name: 'radio', label: 'rádio', Icon: Radio },
  { name: 'podcast', label: 'podcast', Icon: Podcast },
  { name: 'disc', label: 'disco cd', Icon: Disc },
  { name: 'disc-3', label: 'vinil dj', Icon: Disc3 },
  { name: 'music-2', label: 'música', Icon: Music2 },
  { name: 'music-3', label: 'música', Icon: Music3 },
  { name: 'music-4', label: 'música', Icon: Music4 },
  { name: 'piano', label: 'piano teclado', Icon: Piano },
  { name: 'drum', label: 'bateria', Icon: Drum },
  { name: 'speaker', label: 'caixa de som', Icon: Speaker },
  { name: 'volume-2', label: 'volume som', Icon: Volume2 },
  { name: 'video', label: 'vídeo', Icon: Video },
  { name: 'image', label: 'imagem foto', Icon: ImageIcon },
  { name: 'images', label: 'fotos', Icon: Images },
  { name: 'aperture', label: 'fotografia lente', Icon: Aperture },
  { name: 'paint-bucket', label: 'tinta pintor', Icon: PaintBucket },
  { name: 'paint-roller', label: 'pintura parede', Icon: PaintRoller },
  { name: 'pipette', label: 'conta-gotas cor', Icon: Pipette },
  { name: 'drill', label: 'furadeira', Icon: Drill },
  { name: 'axe', label: 'machado', Icon: Axe },
  { name: 'pickaxe', label: 'picareta mineração', Icon: Pickaxe },
  { name: 'shovel', label: 'pá obra', Icon: Shovel },
  { name: 'cog', label: 'engrenagem', Icon: Cog },
  { name: 'settings', label: 'configurações', Icon: Settings },
  { name: 'construction', label: 'obra construção', Icon: Construction },
  { name: 'traffic-cone', label: 'cone trânsito', Icon: TrafficCone },
  { name: 'fuel', label: 'combustível posto', Icon: Fuel },
  { name: 'bus', label: 'ônibus', Icon: Bus },
  { name: 'train', label: 'trem', Icon: Train },
  { name: 'train-front', label: 'trem metrô', Icon: TrainFront },
  { name: 'ship', label: 'navio', Icon: Ship },
  { name: 'sailboat', label: 'veleiro barco', Icon: Sailboat },
  { name: 'plane-takeoff', label: 'viagem decolar', Icon: PlaneTakeoff },
  { name: 'satellite', label: 'satélite', Icon: Satellite },
  { name: 'car-front', label: 'carro', Icon: CarFront },
  { name: 'volleyball', label: 'vôlei', Icon: Volleyball },
  { name: 'goal', label: 'gol futebol', Icon: Goal },
  { name: 'crosshair', label: 'mira', Icon: Crosshair },
  { name: 'mountain-snow', label: 'montanha neve', Icon: MountainSnow },
  { name: 'key', label: 'chave', Icon: Key },
  { name: 'fingerprint', label: 'digital', Icon: Fingerprint },
  { name: 'qr-code', label: 'qr code', Icon: QrCode },
  { name: 'scan-line', label: 'scanner', Icon: ScanLine },
  { name: 'code', label: 'programador código', Icon: Code },
  { name: 'terminal', label: 'terminal programação', Icon: Terminal },
  { name: 'server', label: 'servidor', Icon: Server },
  { name: 'database', label: 'banco de dados', Icon: Database },
  { name: 'infinity', label: 'infinito', Icon: InfinityIcon },
  { name: 'cigarette', label: 'cigarro', Icon: Cigarette },
  { name: 'hop', label: 'lúpulo cerveja', Icon: Hop },
  { name: 'hamburger', label: 'hambúrguer lanchonete', Icon: Hamburger },
  { name: 'vegan', label: 'vegano', Icon: Vegan },
  { name: 'nut', label: 'castanha', Icon: Nut },
  { name: 'ticket', label: 'ingresso', Icon: Ticket },
  { name: 'tickets', label: 'ingressos', Icon: Tickets },
  { name: 'trash-2', label: 'lixo', Icon: Trash2 },
  { name: 'recycle', label: 'reciclagem', Icon: Recycle },
  { name: 'life-buoy', label: 'boia salva-vidas', Icon: LifeBuoy },
  { name: 'binoculars', label: 'binóculos', Icon: Binoculars },
  { name: 'luggage', label: 'mala viagem', Icon: Luggage },
  { name: 'contact', label: 'contato', Icon: Contact },
  { name: 'fan', label: 'ventilador', Icon: Fan },
  { name: 'flashlight', label: 'lanterna', Icon: Flashlight },
  { name: 'heater', label: 'aquecedor', Icon: Heater },
  { name: 'air-vent', label: 'ar condicionado', Icon: AirVent },
  { name: 'bean', label: 'feijão', Icon: Bean },
  { name: 'mic-2', label: 'microfone', Icon: Mic2 },
  { name: 'speech', label: 'fala palestra', Icon: Speech },
  { name: 'presentation', label: 'apresentação aula', Icon: Presentation },
  { name: 'angry', label: 'bravo raiva', Icon: Angry },
  { name: 'frown', label: 'triste', Icon: Frown },
  { name: 'meh', label: 'mais ou menos', Icon: Meh },
  { name: 'annoyed', label: 'irritado', Icon: Annoyed },
]

const ICON_MAP = new Map(CATEGORY_ICONS.map((i) => [i.name, i]))

/** Retorna o ícone salvo ou null (o chamador decide o fallback — emoji). */
export function getCategoryIcon(icon?: string | null): CategoryIconDef | null {
  if (!icon) return null
  return ICON_MAP.get(icon) || null
}
