'use client'

/**
 * Biblioteca de ícones padronizada para categorias (Painel Master).
 *
 * O admin digita o nome da categoria e escolhe um "iconzinho" aqui —
 * assim todas as categorias seguem a mesma linguagem visual no portal.
 *
 * ⚠️ Todos os ícones são do lucide-react (já instalado). Para adicionar
 * um novo, importe o ícone e adicione uma entrada na lista com um label
 * em PT-BR (usado na busca do seletor).
 */
import {
  Anchor,
  Baby,
  Backpack,
  Beer,
  Bike,
  Bird,
  BookOpen,
  Brush,
  Bug,
  Cake,
  Camera,
  Car,
  Cat,
  ChefHat,
  Church,
  Coffee,
  Cookie,
  Cpu,
  Croissant,
  Cross,
  Crown,
  CupSoda,
  Dog,
  Dumbbell,
  Egg,
  Fish,
  Flame,
  Flower,
  Flower2,
  Footprints,
  Gamepad2,
  Ghost,
  Gift,
  GraduationCap,
  Guitar,
  Hammer,
  HardHat,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  IceCream,
  KeyRound,
  Landmark,
  Laptop,
  Laugh,
  Leaf,
  Lock,
  Medal,
  Mic,
  Moon,
  Mountain,
  Music,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  PenTool,
  Pizza,
  Plane,
  Popcorn,
  Rabbit,
  Rainbow,
  Ribbon,
  Rocket,
  Squirrel,
  Snowflake,
  ShoppingBag,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Target,
  TreePine,
  Trophy,
  Truck,
  Turtle,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Wand2,
  Waves,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export type CategoryIconDef = {
  /** slug salvo no banco (Category.icon) */
  name: string
  /** rótulo em PT-BR usado na busca do seletor */
  label: string
  Icon: LucideIcon
}

export const CATEGORY_ICONS: CategoryIconDef[] = [
  { name: 'heart', label: 'amor coração casal', Icon: Heart },
  { name: 'heart-handshake', label: 'amizade gratidão', Icon: HeartHandshake },
  { name: 'coffee', label: 'café caneca morning', Icon: Coffee },
  { name: 'flame', label: 'fogo trendy viral', Icon: Flame },
  { name: 'star', label: 'estrela favorito', Icon: Star },
  { name: 'sparkles', label: 'brilho mágico', Icon: Sparkles },
  { name: 'zap', label: 'energia raio', Icon: Zap },
  { name: 'party-popper', label: 'festa comemoração', Icon: PartyPopper },
  { name: 'cake', label: 'aniversário bolo', Icon: Cake },
  { name: 'gift', label: 'presente brinde', Icon: Gift },
  { name: 'crown', label: 'rei rainha nobre', Icon: Crown },
  { name: 'medal', label: 'medalha premiado', Icon: Medal },
  { name: 'trophy', label: 'troféu campeão', Icon: Trophy },
  { name: 'target', label: 'alvo meta', Icon: Target },
  { name: 'users', label: 'pessoas equipe família', Icon: Users },
  { name: 'baby', label: 'bebê maternidade', Icon: Baby },
  { name: 'graduation-cap', label: 'formatura escola aluno', Icon: GraduationCap },
  { name: 'book-open', label: 'livro leitura estudo', Icon: BookOpen },
  { name: 'pencil', label: 'escola professor', Icon: PenTool },
  { name: 'stethoscope', label: 'médica saúde', Icon: Stethoscope },
  { name: 'syringe', label: 'enfermagem enfermeira vacina', Icon: Syringe },
  { name: 'heart-pulse', label: 'saúde hospital', Icon: HeartPulse },
  { name: 'hard-hat', label: 'engenheiro obra', Icon: HardHat },
  { name: 'wrench', label: 'mecânico ferramenta', Icon: Wrench },
  { name: 'hammer', label: 'marceneiro construção', Icon: Hammer },
  { name: 'paintbrush', label: 'pintor artista', Icon: Paintbrush },
  { name: 'palette', label: 'arte cores criativo', Icon: Palette },
  { name: 'brush', label: 'pincel designer', Icon: Brush },
  { name: 'camera', label: 'fotógrafo foto', Icon: Camera },
  { name: 'music', label: 'música nota', Icon: Music },
  { name: 'guitar', label: 'violão banda', Icon: Guitar },
  { name: 'mic', label: 'cantor karaokê', Icon: Mic },
  { name: 'headphones', label: 'dj som fone', Icon: Headphones },
  { name: 'gamepad2', label: 'games videogame', Icon: Gamepad2 },
  { name: 'laptop', label: 'informática ti', Icon: Laptop },
  { name: 'cpu', label: 'tecnologia', Icon: Cpu },
  { name: 'dumbbell', label: 'academia treino', Icon: Dumbbell },
  { name: 'bike', label: 'bike ciclismo', Icon: Bike },
  { name: 'car', label: 'carro motorista uber', Icon: Car },
  { name: 'truck', label: 'caminhoneiro frete', Icon: Truck },
  { name: 'plane', label: 'avião viagem', Icon: Plane },
  { name: 'anchor', label: 'marinha navio', Icon: Anchor },
  { name: 'rocket', label: 'foguete espaço', Icon: Rocket },
  { name: 'chef-hat', label: 'cozinheiro chef', Icon: ChefHat },
  { name: 'utensils', label: 'restaurante comida', Icon: Utensils },
  { name: 'pizza', label: 'pizza pizzaria', Icon: Pizza },
  { name: 'beer', label: 'cerveja bar chope', Icon: Beer },
  { name: 'wine', label: 'vinho taça', Icon: Wine },
  { name: 'ice-cream', label: 'sorvete', Icon: IceCream },
  { name: 'croissant', label: 'padaria pão', Icon: Croissant },
  { name: 'cookie', label: 'biscoito doce', Icon: Cookie },
  { name: 'popcorn', label: 'pipoca cinema', Icon: Popcorn },
  { name: 'cup-soda', label: 'refrigerante suco', Icon: CupSoda },
  { name: 'egg', label: 'páscoa ovo', Icon: Egg },
  { name: 'paw-print', label: 'pet patinha animal', Icon: PawPrint },
  { name: 'dog', label: 'cachorro dog', Icon: Dog },
  { name: 'cat', label: 'gato miau', Icon: Cat },
  { name: 'bird', label: 'pássaro ave', Icon: Bird },
  { name: 'fish', label: 'peixe pescaria', Icon: Fish },
  { name: 'rabbit', label: 'coelho', Icon: Rabbit },
  { name: 'squirrel', label: 'esquilo', Icon: Squirrel },
  { name: 'turtle', label: 'tartaruga', Icon: Turtle },
  { name: 'bug', label: 'inseto joaninha', Icon: Bug },
  { name: 'flower', label: 'flor primavera', Icon: Flower },
  { name: 'flower-2', label: 'flor delicada madrinha', Icon: Flower2 },
  { name: 'leaf', label: 'folha natureza', Icon: Leaf },
  { name: 'tree-pine', label: 'árvore natal pinheiro', Icon: TreePine },
  { name: 'mountain', label: 'montanha aventura', Icon: Mountain },
  { name: 'sun', label: 'sol verão', Icon: Sun },
  { name: 'moon', label: 'lua noite', Icon: Moon },
  { name: 'rainbow', label: 'arco-íris colorido', Icon: Rainbow },
  { name: 'umbrella', label: 'chuva praia', Icon: Umbrella },
  { name: 'waves', label: 'ondas mar praia', Icon: Waves },
  { name: 'snowflake', label: 'frio inverno natal', Icon: Snowflake },
  { name: 'church', label: 'igreja religião', Icon: Church },
  { name: 'cross', label: 'cruz fé cristã', Icon: Cross },
  { name: 'ghost', label: 'fantasma halloween', Icon: Ghost },
  { name: 'ribbon', label: 'laço outubrosa', Icon: Ribbon },
  { name: 'laugh', label: 'engraçado humor meme', Icon: Laugh },
  { name: 'backpack', label: 'mochila volta às aulas', Icon: Backpack },
  { name: 'shopping-bag', label: 'compras loja', Icon: ShoppingBag },
  { name: 'landmark', label: 'banco financeiro', Icon: Landmark },
  { name: 'wallet', label: 'dinheiro economia', Icon: Wallet },
  { name: 'key-round', label: 'chave senha', Icon: KeyRound },
  { name: 'lock', label: 'cadeado bloqueado', Icon: Lock },
  { name: 'footprints', label: 'pegadas caminhada', Icon: Footprints },
  { name: 'wand', label: 'mágica Harry Potter', Icon: Wand2 },
]

const ICON_MAP = new Map(CATEGORY_ICONS.map((i) => [i.name, i]))

/** Retorna o ícone salvo ou null (o chamador decide o fallback — emoji). */
export function getCategoryIcon(icon?: string | null): CategoryIconDef | null {
  if (!icon) return null
  return ICON_MAP.get(icon) || null
}
